#!/bin/bash

set -e

rm -rf target && mkdir target
./sbt test assembly

rm -rf build && mkdir -p build/modeling/data
cp `ls tile/target/scala-2.10/*.jar` build/modeling/modeling.jar
cp -r tile/data build/modeling
cd build
tar czf modeling.tar.gz modeling
rm -rf modeling

echo "Succesfully built build/modeling.tar.gz"
