#!/bin/bash

set -e

if [[ -n "${GT_TREE_PRIORITIZATION_DEBUG}" ]]; then
    set -x
fi

if [[ -n "${TRAVIS_COMMIT}" ]]; then
    VERSION="${TRAVIS_COMMIT:0:7}"
else
    VERSION="$(git rev-parse --short HEAD)"
fi

function usage() {
    echo -n \
"Usage: $(basename "$0")
Publish images to Amazon ECR
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else

        if [[ -n "${AWS_ECR_ENDPOINT}" ]]; then

            echo "Building gt-tree-prioritization JAR..."
            docker-compose run --rm api-server assembly

            VERSION="${VERSION}" \
            docker-compose -f docker-compose.yml \
                           -f docker-compose.test.yml build \
                              nginx api-server

            eval "$(aws ecr get-login --no-include-email)"

            docker tag "gt-tree-prioritization-nginx:${VERSION}" \
                "${AWS_ECR_ENDPOINT}/gt-tree-prioritization-nginx:${VERSION}"

            docker tag "gt-tree-prioritization:${VERSION}" \
                "${AWS_ECR_ENDPOINT}/gt-tree-prioritization:${VERSION}"
            docker push "${AWS_ECR_ENDPOINT}/gt-tree-prioritization:${VERSION}"
            docker push "${AWS_ECR_ENDPOINT}/gt-tree-prioritization-nginx:${VERSION}"
        else
            echo "ERROR: No AWS_ECR_ENDPOINT variable defined."
            exit 1
        fi

    fi
fi
